# Replace the "âœ" symbol in the prompt with "â¯"
[character]      # The name of the module we are confguring is "character"
#symbol = "â¯"     # The "symbol" segment is being set to "â¯"
success_symbol = "ğŸ¤® "

[git_status]
conflicted = "ğŸ–•"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ‘»"
stashed = "ğŸ“¦"
modified = "ğŸ’©"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
symbol ="ğŸ¹ "
